name: 'AOC leaderboard'
description: 'Private AOC leaderboard to README'
inputs:
  session:
    description: 'AOC session ID.'
    required: true
  leaderboardID:
    description: 'ID of the AOC leaderboard.'
    required: true
  year:
    description: 'The event year. Defaults to current AOC year.'
    required: false
  filename:
    description: 'The markdown file to which the leaderboard should be written. Defaults to /README.md'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
